name: Semantic release 

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install 
        
      - name: Build app
        run: npm run build
        
      - name: Get date and time
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        id: timestamp  # this is used on variable path

      - name: Patch build info
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src/assets/build.json
          field: date
          value: ${{ steps.timestamp.outputs.builddate }}
  
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
